package com.education25.dao.adminDao.coursesControlDao;

import java.sql.Connection;
import com.education25.model.adminModel.coursesControlModel.SubCourseContentRemoveOneSubHeadingModel;

public interface SubCourseContentRemoveOneSubHeadingaDao {
	String removeOneSubHeadingDao(SubCourseContentRemoveOneSubHeadingModel removeOneSubHeadingModel);
	String removeSubHeadingDao(Connection con, SubCourseContentRemoveOneSubHeadingModel removeOneSubHeadingModel);
}