package com.education25.service.adminService.coursesControlService;

import com.education25.model.adminModel.coursesControlModel.SubCourseHeadingUpdateModel;

public interface SubCourseContentUpdateHeadingService {
	String updateHeadingService(SubCourseHeadingUpdateModel subCourseHeadingUpdateModel);
	SubCourseHeadingUpdateModel	checkValidation(SubCourseHeadingUpdateModel subCourseHeadingUpdateModel);
}