package com.education25.service.adminService.coursesControlService;

import com.education25.model.adminModel.coursesControlModel.SubCourseImageGetInformationModel;

public interface SubCourseContentUpdateImageViewService {
	SubCourseImageGetInformationModel getSubcourseImageLinkService(String sub_course_short_id);
}