package com.education25.service.adminService.coursesControlService;

import com.education25.model.adminModel.coursesControlModel.SubCourseContentAddOneSubHeadingFormModel;

public interface SubCourseContentAddOneSubHeadingService {
	String addOneSubHeadingService(SubCourseContentAddOneSubHeadingFormModel subHeadingFormModel);
	SubCourseContentAddOneSubHeadingFormModel CheckValidationService(SubCourseContentAddOneSubHeadingFormModel subHeadingFormModel);
}