package com.education25.service.adminService.coursesControlService;

import com.education25.model.adminModel.coursesControlModel.SubCoursesContentListAndMessageModel;

public interface SubCourseContentUpdateFormService {
	SubCoursesContentListAndMessageModel getinformationBasedOnAdminService(int AdminId);
}